use_frameworks!

platform :ios, '13.0'

target 'TokenTrek' do
  pod 'SnapKit'
  pod 'Charts'
  pod 'Moya'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase/Core'
  pod 'FirebaseDatabase'
end
